apiVersion: 2019-12-01
location: northeurope
name: SQLAppGroup
properties:
  containers: 
  - name: db
    properties:
      image: companyregistry.azurecr.io/appsqlimage:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 3306
  - name: web
    properties:
      image: companyregistry.azurecr.io/sqlapp:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 80          
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
  imageRegistryCredentials:
    - server: companyregistry.azurecr.io
      username: companyregistry
      password: u0K36bwuW4E85jUFQL6l6d/jEtf7wA71
type: Microsoft.ContainerInstance/containerGroups